# Paths here are relative to container binding

# PLINK1.9 file prefix with path
  # must be a single file, but file can contain one or multiple chromosomes
plink_prefix: "/data/input/daisyexome"
out_dir: "/data"  # top-level directory for all output
code_dir: "/repo"  # top-level of topmed_imputation repo in
chr: "21"  # either one chr number or "all"
orig_build: "hg38"  #  either hg19 or hg 38
to_build: ""  # either hg19 or hg38
chr6_hwe: = "no"  # either "yes" for chr6 different HWE filter or "no" for same

#TODO: do I need an MIS or TM indicator?